apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftp.fullname" . }}-host-keys
  labels:
    app: {{ include "sftp.name" . }}
    chart: {{ include "sftp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  ssh_host_ed25519_key: |-
{{ .Values.sshHostKeys.ed25519.private | indent 4 }}
  ssh_host_ed25519_key.pub: |-
{{ .Values.sshHostKeys.ed25519.public | indent 4 }}
  ssh_host_rsa_key: |-
{{ .Values.sshHostKeys.rsa.private | indent 4 }}
  ssh_host_rsa_key.pub: |-
{{ .Values.sshHostKeys.rsa.public | indent 4 }}
