{{- if .Values.security.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.security.serviceAccount.name }}
  labels:
    app: {{ include "sftp.name" . }}
    chart: {{ include "sftp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
