apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp.fullname" . }}
  labels:
    app: {{ include "sftp.name" . }}
    chart: {{ include "sftp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
      protocol: TCP
      name: ssh
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "sftp.name" . }}
    release: {{ .Release.Name }}
